spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: root
    password: waduclay

    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    application:
      name: order-service
server:
  port: 8070
application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments
